# Deriving from latest base image
FROM python:latest

# Labels as key value pair
LABEL Maintainer="satya-ranjan"

# Any working direcotory can be chosen as per choice 
WORKDIR ./

CMD [ "./test.py" ]


