- name: Create EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        key_name: OhioKeypair
        instance_type: t2.micro
        image_id: ami-0a695f0d95cefc163
        region: us-east-2
        security_group: sg-094aea2187ef45618
        tags:
          Name: ca3-instance
        wait: true
        vpc_subnet_id: subnet-014e2977a01ee1923
        network:
          assign_public_ip: true
      register: ec2
    - name: Print Public IP Address
      debug:
        msg: "Instance IP address is {{ ec2.instances[0].network_interfaces[0]['association']['public_ip'] }}"
